### ISSUE TITLE
Error in workflow: [family] missing

### ISSUE THREAD

**Issue by ghost** [alanzchen/zotero-better-bibtex-alfred#2]
Hello. The workflow stopped working for me. I am available for more information. Thank you in advance!

```
Starting debug for 'Zotero citekey'

[2019-05-27 13:57:14][ERROR: input.scriptfilter] Code 1: .
13:57:14 workflow.py:2057 DEBUG    ---------- Zotero citekey ----------
13:57:14 connectionpool.py:205 DEBUG    Starting new HTTP connection (1): localhost:23119
13:57:14 connectionpool.py:393 DEBUG    http://localhost:23119 "POST /better-bibtex/json-rpc HTTP/1.1" 200 None
13:57:14 workflow.py:2074 ERROR    'family'
Traceback (most recent call last):
  File "/Users/jakub/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F8EF130-28A4-4941-9847-DAFE5ADDF525/workflow/workflow.py", line 2067, in run
    func(self)
  File "/Users/jakub/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F8EF130-28A4-4941-9847-DAFE5ADDF525/search.py", line 33, in main
    authors = [j['family'] for j in i['author']]
KeyError: 'family'
13:57:14 workflow.py:2097 DEBUG    ---------- finished in 0.135s ----------
[2019-05-27 13:59:49][ERROR: input.scriptfilter] Code 1: .
13:59:49 workflow.py:2057 DEBUG    ---------- Zotero citekey ----------
13:59:49 connectionpool.py:205 DEBUG    Starting new HTTP connection (1): localhost:23119
13:59:49 connectionpool.py:393 DEBUG    http://localhost:23119 "POST /better-bibtex/json-rpc HTTP/1.1" 200 None
13:59:49 workflow.py:2074 ERROR    'family'
Traceback (most recent call last):
  File "/Users/jakub/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F8EF130-28A4-4941-9847-DAFE5ADDF525/workflow/workflow.py", line 2067, in run
    func(self)
  File "/Users/jakub/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F8EF130-28A4-4941-9847-DAFE5ADDF525/search.py", line 33, in main
    authors = [j['family'] for j in i['author']]
KeyError: 'family'
13:59:49 workflow.py:2097 DEBUG    ---------- finished in 0.242s ----------
```

**Comment by alanzchen** [comment]
The latest commit should fix this issue. Let me know if it works for you.

**Comment by ghost** [comment]
It works! Thank you soooo much!
